AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  BucketPrefix:
    Description: The prefix to use for the S3 bucket
    Type: String
    Default: 'development'
  CodeCommitRepositoryName:
    Description: This is the CodeCommit repository name
    Type: String
    MinLength: 1
    Default: 'website-development'
Resources:
  WebBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'website-bucket-${BucketPrefix}-${AWS::AccountId}-${AWS::Region}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  WebBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref WebBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join ['', ['arn:aws:s3:::', !Ref WebBucket, '/*']]
  WebCloudFront:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - DomainName: !GetAtt [WebBucket, DomainName]
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: ''
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
  MyCodeCommitRepository:
    Type: 'AWS::CodeCommit::Repository'
    Properties:
      RepositoryName: !Ref CodeCommitRepositoryName
      RepositoryDescription: 'This is my CodeCommit Repository'
Outputs:
  CloudFrontDistributionDomainName:
    Description: The domain name of the CloudFront distribution.
    Value: !GetAtt [WebCloudFront, DomainName]
